import type { AccountStatus } from "./accounts/types"
import type { AgentMetadata } from "./agents/discovery"
import type { PriceChange } from "./domain/changes"
import type { ProviderSnapshot } from "./domain/provider"
import { isFreePricing } from "./domain/model"
import { rankOffers } from "./domain/ranking"
import { assessAgent } from "./agents/assessment"
import type { AiResult } from "./ai"
import { randomBytes } from "crypto"

export interface DashboardState { snapshots: ProviderSnapshot[]; history: PriceChange[]; agents: AgentMetadata[]; accounts: AccountStatus[]; ai: AiResult | null; updatedAt: number }
const esc = (value: unknown) => String(value ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")
const offers = (state: DashboardState) => state.snapshots.flatMap((snapshot) => snapshot.offers)

export function panelHtml(state: DashboardState): string {
  const nonce = randomBytes(16).toString("base64")
  const all = offers(state), free = all.filter((offer) => isFreePricing(offer.pricing)).length
  const modelRows = all.slice().sort((a,b)=>(a.pricing.input+a.pricing.output)-(b.pricing.input+b.pricing.output)).map((offer)=>`<tr data-model="${esc(`${offer.name} ${offer.provider} ${offer.capabilities.purposes.join(" ")}`.toLowerCase())}" data-provider="${esc(offer.provider)}" data-price="${isFreePricing(offer.pricing) ? "free" : "paid"}"><td>${esc(offer.name)}</td><td>${esc(offer.provider)}</td><td>${offer.pricing.input}</td><td>${offer.pricing.output}</td><td>${esc(offer.capabilities.purposes.join(", "))}</td></tr>`).join("")
  const assessments = state.agents.map((agent)=>assessAgent(agent, all))
  const agents = assessments.length ? assessments.map(({agent,status,reason,alternative})=>`<div class="row"><span>${esc(agent.name)} · ${esc(agent.model)}<small class="muted"> ${esc(reason)}</small></span><b>${esc(status)}${alternative ? ` → ${esc(alternative.name)}` : ""}</b></div>`).join("") : `<div class="muted">Keine Agenten erkannt</div>`
  const accounts = state.accounts.map((account)=>`<div class="row"><span>${esc(account.provider)}</span><b>${esc(account.remainingUsd ?? account.message ?? account.state)}</b></div>`).join("") + `<div><button data-action="connect">Konto verbinden</button> <button data-action="disconnect">Verbindung entfernen</button></div>`
  const topFree = rankOffers(all,"coding","free").slice(0,3), topPaid = rankOffers(all,"coding","paid").slice(0,3)
  const ranks = (items: typeof topFree) => items.length ? items.map((item,index)=>`${index+1}. ${esc(item.offer.name)}${item.score === null ? " · noch nicht bewertet" : ` · ${item.score}`}`).join("<br>") : "Keine bewertbaren Modelle"
  return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta http-equiv="content-security-policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}'"><style>
  :root{color-scheme:light dark}*{box-sizing:border-box}body{font:var(--vscode-font-size) var(--vscode-font-family);color:var(--vscode-foreground);margin:0;padding:10px;background:linear-gradient(145deg,var(--vscode-editor-background),color-mix(in srgb,var(--vscode-editor-background) 88%,#4c1d95))}.nav{display:flex;gap:16px;align-items:center;border-bottom:1px solid var(--vscode-panel-border);padding:3px 2px 7px}.nav button{background:none;color:inherit;border:0;padding:0;cursor:pointer}.metrics{display:flex;gap:28px;padding:7px 2px;flex-wrap:wrap}.metrics b{font-size:1.35em}.insight{border-left:2px solid #a78bfa;background:#8b5cf61a;padding:4px 7px;margin-bottom:5px}.grid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:5px;align-items:start}.card{background:var(--vscode-editorWidget-background);border:1px solid var(--vscode-panel-border);border-radius:7px;padding:5px 7px}.row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px;padding:2px 0;border-bottom:1px solid color-mix(in srgb,var(--vscode-panel-border) 45%,transparent)}.view[hidden]{display:none}.muted{color:var(--vscode-descriptionForeground)}table{width:100%;border-collapse:collapse}td,th{padding:4px;border-bottom:1px solid var(--vscode-panel-border);text-align:left}@media(max-width:1000px){.grid{grid-template-columns:1.5fr 1fr}.accounts{grid-column:2}}@media(max-width:700px){.grid{grid-template-columns:1fr}.accounts{grid-column:auto}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:6px 14px}}
  </style></head><body><nav class="nav"><b>Preis-Watch</b><button data-view="overview">Übersicht</button><button data-view="models">Modelle</button><button data-view="agents">Agenten</button><button data-view="accounts">Konten &amp; Limits</button><span style="margin-left:auto">● aktuell</span></nav>
  <section class="view" id="overview"><div class="metrics"><span><b>${all.length}</b> Modelle</span><span><b>${free}</b> kostenlos</span><span><b>${state.history.length}</b> Änderungen</span><span><b>${state.agents.length}</b> Agenten</span></div><div class="insight"><b>✦ KI-Fazit</b> ${esc(state.ai?.text ?? "Rankings und Preisänderungen werden lokal ausgewertet.")}</div><div class="grid"><div class="card"><b>Beste Modelle für deinen Zweck</b><div class="row"><span><b>Kostenlos · Coding</b><br>${ranks(topFree)}</span><span><b>Bezahlt · Coding</b><br>${ranks(topPaid)}</span></div><p class="muted">Coding · Sprache · Reasoning · Vision · Tools · Allround</p></div><div class="card"><b>Deine Agenten</b>${agents}</div><div class="card accounts"><b>Konten &amp; Limits</b>${accounts}</div></div></section>
  <section class="view" id="models" hidden><h2>Alle Modelle</h2><input id="search" placeholder="Modelle durchsuchen"> <select id="provider"><option value="">Alle Anbieter</option><option>openrouter</option><option>opencode-zen</option><option>opencode-go</option></select> <select id="price"><option value="">Kostenlos &amp; bezahlt</option><option value="free">Kostenlos</option><option value="paid">Bezahlt</option></select><table><thead><tr><th>Modell</th><th>Anbieter</th><th>Input / 1M</th><th>Output / 1M</th><th>Fähigkeiten</th></tr></thead><tbody>${modelRows}</tbody></table></section>
  <section class="view" id="agents" hidden><h2>Deine Agenten</h2>${agents}</section><section class="view" id="accounts" hidden><h2>Konten &amp; Limits</h2>${accounts}</section>
  <script nonce="${nonce}">const vscode=acquireVsCodeApi();document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==b.dataset.view)}));document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>vscode.postMessage({type:b.dataset.action})));const filter=()=>{const q=document.getElementById('search').value.toLowerCase(),p=document.getElementById('provider').value,c=document.getElementById('price').value;document.querySelectorAll('[data-model]').forEach(r=>r.hidden=!(r.dataset.model.includes(q)&&(!p||r.dataset.provider===p)&&(!c||r.dataset.price===c)))};['search','provider','price'].forEach(id=>document.getElementById(id).addEventListener(id==='search'?'input':'change',filter));</script></body></html>`
}
